apiVersion: apps/v1
kind: Deployment
metadata:
  name: Maintanence1
spec:
  replicas: 3 # Number of instances of the application to run
  selector:
    matchLabels:
      app: maintanence-1
  template:
    metadata:
      labels:
        app: maintanence-1
    spec:
      containers:
        - name: maintanence-1
          image: maintanence-1:latest
          ports:
            - containerPort: 8080 # Port that the application listens on

---

apiVersion: v1
kind: Service
metadata:
  name: maintanence-1-service
spec:
  selector:
    app: maintanence-1
  ports:
    - protocol: TCP
      port: 80 # Port that the service listens on
      targetPort: 8080 # Port that the application listens on
  type: LoadBalancer # Configures the service for load balancing
